mysql:
  dsn: "landmark:landmark@csmsu@tcp(202.28.34.197:3306)/landmark?collation=utf8mb4_unicode_ci&parseTime=true"
  # username=landmark,pass=landmark@csmsu,port=202.28.34.197:3306,namedata=landmark